apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp-container
        image: localhost/helloapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloapp-service
spec:
  type: NodePort
  selector:
    app: helloapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
